### ISSUE TITLE
Idea for collaboration

### ISSUE THREAD

**Issue by gitonthescene** [orgapp/orgajs#105]
Hello,  I found your project from the [worg tools list](https://orgmode.org/worg/org-tools/index.html).  First, sorry for the semi-spam nature of this issue.  I had a notion for a project that the org community might find useful and I'm looking for feedback.  Feel free to close this issue if it doesn't sound useful to you.

My idea is to start a [list of org-mode snippets](https://github.com/gitonthescene/org-mode-samples) which can serve as a test bed for people developing tools.  The idea is that having a separate collection of examples makes it easier for others in the community to benefit from the examples developed through communication with users.

Users could use these samples to try to construct minimal examples of issues they're having and/or contribute examples there which others could benefit from.  Exactly how it will take shape is still up in the air.

These samples could also serve as a place to discuss ideas about how to develop the grammar itself.  According to worg, the spec is still in [draft state](https://orgmode.org/worg/dev/org-syntax.html).

There's not much there at the moment.  Mostly because I don't want to commit too early to what seems like it might be useful.  I'll add more examples as I go.

If you like the concept and/or want to contribute and/or just want to offer feedback, I'd very much appreciate it.

Again, sorry for the spam.

**Comment by GuiltyDolphin** [comment]
Hi @gitonthescene.

Have you seen [org-babel-examples](https://github.com/dfeich/org-babel-examples)? They have some examples of Org already, though it is by no means comprehensive. It could be worth pinging them to find out if they have future plans to cover other parts of the syntax.

In terms of our use for this, @xiaoxinghu would know more, but it might be too much of a dependency to rely on an external source of snippets for testing. Our internal base of examples is growing over time as we add/change functionality, but of course an external reference could be useful to catch any examples we might have missed.

Regarding a formal grammar - I'm working on one locally based on the draft, which should help to make sure we support the spec as it is laid out (or know when we are deviating). Org itself parses some things in ways that don't seem to be implied by the spec, so there is some ambiguity on occasion.

**Comment by gitonthescene** [comment]
Thanks for getting back.  I had not seen org-babel-examples.  I will reach out to them.

I actually started taking a stab at writing a PEG grammar for org-mode.  Reading the spec carefully reveals that parts are imprecisely worded.  That means that the parsers out there have made their own decisions as to what is meant by the spec.  This is what got me started.  I thought if we had a core set of examples demonstrating all the behavior that might be a good place to work on a consensus.

The thing is that the philosophy behind org-mode is that “it’s just plain text” which means the `org-element.el` parser is pretty permissive.  But that makes it harder to write tools that interface with it.

In any event, I admit that my ideas aren’t fully fleshed out.  I was just trying to get a feel for who the stake holders might be.

I’ll close this issue for now.  If you have any further ideas feel free to open an issue.

FWIW, I’ve attached my thumbnail sketch of a PEG grammar.  It needs a lot of work.

Thanks again

[org-mode-grammar.txt](https://github.com/orgapp/orgajs/files/6764233/org-mode-grammar.txt)

**Comment by gitonthescene** [comment]
FWIW, someone already created an EBNF [here](https://github.com/200ok-ch/org-parser/blob/master/resources/org.ebnf).  You might want to reach out to them.  Pay particular attention to the license, though.

**Comment by gitonthescene** [comment]
Here’s [another](https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00382.html).

FWIW, I have [another proposal](https://orgmode.org/list/28097ae6-bd9a-6842-7600-97b220375fbb@yahoo.com/T/#t) which could smooth over the adoption of a supported strict syntax.

**Comment by GuiltyDolphin** [comment]
Thanks @gitonthescene ! I agree the situation isn't great at the moment - and considering the way in which the Elisp Org parser and spec have inconsistencies, one usually has to make their own choices about which to follow in each case of an inconsistency when implementing a parser.

I'm trying out a parser combinator style which I'm hoping will be flexible enough to allow us to adapt if/when things settle with the grammar.
