### ISSUE TITLE
orga v2.5.0 has breaking changes

### ISSUE THREAD

**Issue by BlackGlory** [orgapp/orgajs#125]
According to semver, `^2.4.9` will install `2.5.0`, but the AST output has been modified and it is not compatible.

**Comment by xiaoxinghu** [comment]
yes! you are right. Maybe I am using Lerna wrong, but I failed to let it recognise `BREAKING CHANGE`s from my commit messages. I have asked about it [here](https://github.com/lerna/lerna/issues/2668#issuecomment-907552798). In the meantime I am looking at other solutions.

**Comment by xiaoxinghu** [comment]
@BlackGlory I have replaced `Lerna` with `changeset`, now everything seems to work as expected. I have re-published the packages on 3.0.0, deprecated 2.5.0 and 2.6.0. Hopefully, it won't cause a lot of trouble. 🤞
