### ISSUE TITLE
Tags can contain '@' symbol

### ISSUE THREAD

**Issue by kolya-ay** [orgapp/orgajs#39]
According to docs: https://orgmode.org/guide/Tags.html

**Comment by gitonthescene** [comment]
Can you describe more explicitly the issue you are having?   What input is generating what unexpected output?

**Comment by tvooo** [comment]
I may be able to shed some light on this.

Currently, the parser seems to ignore when tags include an `@`. For example, a headline such as

```* This is a headline :tag:```

will correctly return

```
{
      "type": "headline",
      "children": [
        {
          "type": "text",
          "value": "This is a headline"
        }
      ],
      "level": 1,
       "tags": ["tag"],
    },
```

whereas 
```* This is a headline :tag:```

will return

```
{
      "type": "headline",
      "children": [
        {
          "type": "text",
          "value": "This is a headline :@tag:"
        }
      ],
      "level": 1,
    },
```

However, as @kolya-ay points out, `@` characters are completely valid according to the spec, so I guess that's a bug in the parser. :)

**Comment by gitonthescene** [comment]
Thanks.  Pull request #58 fixes this.

**Comment by tvooo** [comment]
Amazing, thank you @gitonthescene

**Comment by xiaoxinghu** [comment]
should be fixed right now. I think it was fixed in stable version too. but [check it out in v2](https://orga.js.org?text=*%20This%20is%20a%20headline%20%3A%40tag%3A) and please let me know if there are any new issues.
