### ISSUE TITLE
footnotes are not parsed

### ISSUE THREAD

**Issue by otech-nl** [orgapp/orgajs#42]
Hello,

Thank you for your effort to provide us with this software! A bridge between org and the web really adds to my org mode experience.

I am currently using orga as part of https://www.gatsbyjs.org/packages/gatsby-transformer-orga/. It works very well, except for [footnotes](https://orgmode.org/manual/Footnotes.html). Markup like `[fn:this is a footnote]` is rendered fine by Emacs but not at all by orga. See this [example](https://dwim.nl/10-minute-org-mode-101).

Your [example](https://orga.js.org/syntax) suggests orga supports footnotes. So, what am I doing wrong?

**Comment by fullofcaffeine** [comment]
I'd like to know as well, I'm currently trying to get hold of footnotes in some org files through orga. Any insights?

**Comment by otech-nl** [comment]
No, nothing yet

**Comment by thomasheartman** [comment]
I'm sure this isn't really helpful for existing files, but at least for newer files, using the footnote system where they're put at the bottom of the document works and referenced works just fine:
```org
If you have a footnote like this[fn:1]

* Footnotes

[fn:1] then orga will pick this up
```

This is also how it's done in the example referenced above. The source for that example is [here](https://raw.githubusercontent.com/orgapp/gatsby-orga/master/src/pages/syntax.org)

**Comment by xiaoxinghu** [comment]
@otech-nl  Sorry for the late reply, in v2 (still in beta), it works fine for both footnote reference and footnote definition. Check it out [here](https://orga.js.org?text=this%5Bfn%3Amy_footnote%5D%20is%20a%20footnote%20reference.%0A%0A%5Bfn%3Amy_footnote%5D%20this%20is%20the%20footnote%20definition.). I am not sure if it works the same way in v1.x anymore. But you can try it out now by using the `next` version. (e.g. `yarn add orga@next`), I will try to release v2 soon.

**Comment by otech-nl** [comment]
Thanks for your response. I will give it a try.
