### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by gitonthescene** [orgapp/orgajs#50]
Hi there,

The [license](https://en.wikipedia.org/wiki/MIT_License) is clear in all the respective package.json files, but it would be clearer to add a LICENSE.org file at the top level in the repository.  It would also work better with [various tools](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository).

**Comment by gitonthescene** [comment]
Given that there’s no dialog on this project.  I’ll probably stop submitting pull requests and simply fork and rename.

**Comment by xiaoxinghu** [comment]
LICENSE added. Thanks 😉
