### ISSUE TITLE
Broken links from gatsby documentation

### ISSUE THREAD

**Issue by kepi** [orgapp/orgajs#53]
Hello,

after transfer to `orgapp` organization, links from https://www.gatsbyjs.org/packages/gatsby-transformer-orga/ are not working. It took me some time to find documentation again, google wasn't much help :)

Looks like it is taking info from `package.json` as same info is presented on npmjs.

**Comment by gitonthescene** [comment]
Do you have a reproducible case?  Is there a repository on github I can clone to see the issue?  Ideally it would be a really simple example to isolate the problem.

**Comment by kepi** [comment]
I'm not sure from where is `gatsby-transformer-orga` building, but I'm talking about the problem with this package, not of some my project.

As you can see in gatsbyjs doc or in npmjs pages, links from `gatsby-transformer-orga` points to https://xiaoxinghu.github.io/orgajs/docs/generate-static-website-with-gatsby instead of https://orga.js.org/docs/generate-static-website-with-gatsby

**Comment by gitonthescene** [comment]
Ah, this about the links on the gatsbyjs.org website?  This would have to be fixed there.  I'm not sure where that code is, but it's not [where I would expect it to be](https://github.com/gatsbyjs/gatsby/tree/master/packages).  Maybe that doc needs to be removed?

Maybe you can open an issue on that repository.

FWIW, I believe that gatsby-transformer-orga is [now available in this repository](https://github.com/orgapp/orgajs/tree/master/packages/gatsby-transformer-orga)

**Comment by kepi** [comment]
Yeah, I opened the issue here because it was wrong in the package README. Looks fixed now (https://www.npmjs.com/package/gatsby-transformer-orga). Gatsby docs is maybe not auto updated so often (or not updated at all?), I'll opened the issue gatsbyjs/gatsby#25541
