### ISSUE TITLE
Issue with React Native

### ISSUE THREAD

**Issue by qhuyduong** [orgapp/orgajs#54]
Hi,

Thanks for this great package. I'm trying to use `orga-rehype` for my react native project. However whenever I import `orga-rehype`, this error is printed out forever.

![image](https://user-images.githubusercontent.com/16358771/86072241-57986300-baab-11ea-88e5-b3c8b0837a0f.png)

Any idea why?

TIA

**Comment by gitonthescene** [comment]
It's tough to debug with this description.  Is your project on github?  Are you saying that only importing `orga-rehype` generates this error and if you don't import it you don't get this error?

**Comment by qhuyduong** [comment]
@gitonthescene my project is not on github. 

Yes only importing orga-rehype generates this error. I tried several times. When I import other packages like `orga` or `orga-unified` there is no issue.

**Comment by gitonthescene** [comment]
You'll still need to provide an example.  I don't see this error in any of my projects.
