### ISSUE TITLE
Why no DEADLINE: and SCHEDULED: ?

### ISSUE THREAD

**Issue by stephenBDT** [orgapp/orgajs#55]
I was just trying this on your site:  https://orga.js.org

```
* TODO [#B] Review code :work:
DEADLINE: <2020-07-03 Fri> SCHEDULED: <2020-07-03 Fri>
```
I get:
```
{ type: 'root',
  children: 
   [ { type: 'section',
       children: 
        [ { type: 'headline',
            children: 
             [ { type: 'text',
                 children: [],
                 value: 'Review code',
                 parent: [Circular] },
               { type: 'planning',
                 children: [],
                 keyword: 'DEADLINE',
                 parent: [Circular] } ],
            level: 1,
            keyword: 'TODO',
            priority: 'B',
            tags: [ 'work' ],
            parent: [Circular] } ],
       level: 1,
       parent: [Circular] } ],
  meta: {} }
```

When I put a newline between the two keywords it looks a bit better, but the SCHEDULED is still not there:
```
* TODO [#B] Review code :work:
DEADLINE: <2020-07-03 Fri> 
SCHEDULED: <2020-07-03 Fri>
```
results in:
```
{ type: 'root',
  children: 
   [ { type: 'section',
       children: 
        [ { type: 'headline',
            children: 
             [ { type: 'text',
                 children: [],
                 value: 'Review code',
                 parent: [Circular] },
               { type: 'planning',
                 children: [],
                 keyword: 'DEADLINE',
                 date: Thu Jul 02 2020 00:00:00 GMT+0200 (Central European Summer Time),
                 end: undefined,
                 parent: [Circular] } ],
            level: 1,
            keyword: 'TODO',
            priority: 'B',
            tags: [ 'work' ],
            parent: [Circular] } ],
       level: 1,
       parent: [Circular] } ],
  meta: {} }
```

I am wondering why they do not get parsed as of https://orgmode.org/manual/Inserting-deadline_002fschedule.html

Did i understand something wrong, or is is a yet unimplemented feature or is it a bug?

Thank you for this work! It seems very promising!

**Comment by gitonthescene** [comment]
It looks like `planning` nodes are only parsed as part of a `heading` and [only one `planning` type node is expected](https://github.com/orgapp/orgajs/blob/master/packages/orga/src/processors/headline.ts#L40).  This can probably easily turned into a while, but that would mean that such nodes are expected to be all in a row after the heading, which would at least handle your second case.  Actually, there is a [footnote](https://orgmode.org/manual/Inserting-deadline_002fschedule.html#DOCF65) in the doc you posted which suggests that this may be okay.

As for your first case, the parser is currently line oriented and doesn't recognize this as two separate tokens.   Some work was done in #47 to help with this, but it doesn't currently handle this case either.  I can try to take a look to improve it to handle this as well, though.

**Comment by gitonthescene** [comment]
With both #56 and #57 both these cases should be handled.

**Comment by xiaoxinghu** [comment]
should be fixed in v2 (the `next` version). Check out the syntax tree [here](https://orga.js.org/?text=*%20TODO%20%5B%23B%5D%20Review%20code%20%3Awork%3A%0ADEADLINE%3A%20%3C2020-07-03%20Fri%3E%20SCHEDULED%3A%20%3C2020-07-03%20Fri%3E). You can try it out by `yarn add orga@next`.
