### ISSUE TITLE
Tags are not recognized from headline

### ISSUE THREAD

**Issue by Plurax** [orgapp/orgajs#74]
Hi,

I am having the issue that tags are not extracted from headlines. I am working on a modified gatsby blog with i18n.
I have two different org files in the content folder, one is having a global tag setting in he header (which works):
`
#+TAGS: testTag
`
another file is only using headers:
`
#+ORGA_PUBLISH_KEYWORD: PUBLISHED
#+TODO: DRAFT | PUBLISHED

* PUBLISHED A headline               :aTag:
  CLOSED: [2020-06-16 Do 11:42]
  :PROPERTIES:
  :lang:     de
  :END:

A post from 2020

If I enter http://localhost:8000/__graphql I can see the tags from the head definition, but not the ones defined besides a headline.

package-lock.json part:
`
    "gatsby-transformer-orga": {
      "version": "2.1.5",
      "resolved": "https://registry.npmjs.org/gatsby-transformer-orga/-/gatsby-transformer-orga-2.1.5.tgz",
      "integrity": "sha512-WleorfHj9DLQPouZ4Bs7B3XNWlV5UKytCPj0czikVdTKlq9hO+RlT1I6ibbQBThmcxxjZL1v+STHhg3pTY2osg==",
      "requires": {
        "bluebird": "^3.7.0",
        "hast-util-to-html": "^7.1.1",
        "is-relative-url": "^3.0.0",
        "mime": "^2.4.4",
        "moment": "^2.24.0",
        "oast-to-hast": "^2.1.5",
        "orga": "^2.1.5",
        "rehype-stringify": "^8.0.0",
        "unified": "^9.1.0",
        "unist-builder": "^2.0.3",
        "unist-util-map": "^2.0.1",
        "unist-util-select": "^3.0.1",
        "unist-util-visit": "^2.0.3"
      },
`
I am sure this worked before, but I unfortunately I can not remember the version I had before...
(I am not a ja/npm pro - I just wanted to get a blog running with org mode)

BR
Plurax

**Comment by xiaoxinghu** [comment]
@Plurax, thanks for the detailed description. Correct me if I misunderstood: you want the `tags` of that headline to be the concatenation of the `#+TAGS` at the top of the file and the tags found on the headline itself. If that's the case, I think in org-mode itself, `#+TAGS` is not automatically applied to all headlines of that file, it is used to construct a list of "preferred tags" for the popup when you try to insert tags to a headline.

**Comment by Plurax** [comment]
Hi @xiaoxinghu 

not exactly: In my setup, the tags are parsed correctly and are visible within graphql, if they are set in the #+TAGS header.
The tags from the headlines in the file are not set at all. I can not find them in graph ql.
Below a test file I want to use for future posts.
`
#+ORGA_PUBLISH_KEYWORD: PUBLISHED
#+TODO: DRAFT | PUBLISHED
* PUBLISHED A headline               :aTag:
  CLOSED: [2020-06-16 Do 11:42]
  :PROPERTIES:
  :lang:     de
  :END:

A post from 2020

* PUBLISHED An other headline                               :anotherHeadline:
  CLOSED: [2020-11-06 Fr 21:55]
  :PROPERTIES:
  :lang:     de
  :END:

This is another headline with another tag.
`

**Comment by xiaoxinghu** [comment]
@Plurax can you take a look at the [updated starter project](https://github.com/orgapp/gatsby-starter-blorg), it has all the latest stuff. Maybe create a new project with it ([it's very simple to do now](https://orgapp.github.io/gatsby-starter-blorg/getting-started/getting-started)), put your org files into the `content` folder, see if you can reproduce it. Please let me know if you have any issues with that.

**Comment by Plurax** [comment]
@xiaoxinghu thanks - I created a new app from scratch and its working. May be I just mixed things up with my own target of i18n compatibility, but thats not an issue with your plugin. Thank you!
